name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for proper versioning

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Extract version from tag
      id: get_version
      shell: pwsh
      run: |
        $tag = "${{ github.ref_name }}"
        $version = $tag -replace '^v', ''
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "TAG=$tag" >> $env:GITHUB_OUTPUT
        echo "Building version: $version"

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Release
      run: |
        dotnet publish `
          --configuration Release `
          --no-restore `
          --output publish-output `
          /p:Version=${{ steps.get_version.outputs.VERSION }} `
          /p:AssemblyVersion=${{ steps.get_version.outputs.VERSION }} `
          /p:FileVersion=${{ steps.get_version.outputs.VERSION }} `
          /p:InformationalVersion=${{ steps.get_version.outputs.VERSION }}

    - name: Prepare artifacts
      shell: pwsh
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"

        # Create release directory
        New-Item -ItemType Directory -Force -Path "release-artifacts"

        # Copy all DLLs from publish output (excluding dependencies if needed)
        Copy-Item "publish-output\*.dll" -Destination "release-artifacts\" -Include "COM3D2.*.dll"

        # Create zip archive
        Compress-Archive -Path "release-artifacts\*" -DestinationPath "COM3D2.UndressUtil-$version.zip"

        # List artifacts
        Write-Host "Files in release-artifacts:"
        Get-ChildItem -Path "release-artifacts" -Recurse
        Write-Host "`nZip file created:"
        Get-ChildItem -Path "COM3D2.UndressUtil-$version.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          COM3D2.UndressUtil-${{ steps.get_version.outputs.VERSION }}.zip
        body: |
          ## COM3D2.UndressUtil ${{ steps.get_version.outputs.TAG }}

          ### Changes
          See commit history for details.

          ### Installation
          1. Download `COM3D2.UndressUtil-${{ steps.get_version.outputs.VERSION }}.zip`
          2. Extract the DLL files to your game's plugin directory
          3. Restart the game
        draft: true
        prerelease: ${{ contains(steps.get_version.outputs.VERSION, '-') }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: InOutAnimation-${{ steps.get_version.outputs.VERSION }}
        path: release-artifacts/*.dll
        retention-days: 90
